---
title: "Data exploration Europe"
author: "Nik Seldon"
date: "26 3 2020"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##COVID-19-Analysis
### Phase of exponential growth in Europe

#### Include R libraries
```{r message=FALSE, warning=FALSE, echo=TRUE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
```


```{r message=FALSE, warning=FALSE,echo=FALSE}
if(.Platform$OS.type == "windows") {
     setwd("C:/Users/domin/OneDrive/covid/")} else {
         setwd("~/OneDrive/covid/")}

cwd<-getwd()
```

#### Getting Data

COVID-19 ata provided by the Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE), 
and is taken from their Github repository[https://github.com/CSSEGISandData/COVID-19] https://github.com/CSSEGISandData/COVID-19), Novel Coronavirus (COVID-19) Cases.

```{r message=FALSE, warning=FALSE,echo=TRUE}
#URLS
github<-"https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/"
confirmedURL_JHU <-paste(github,"csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv?accessType=DOWNLOAD", sep="")
deathURL_JHU<-paste(github,"csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv?accessType=DOWNLOAD", sep="")
```

```{r message=FALSE, warning=FALSE}
#DOWNLOAD
dateDownloaded<-Sys.Date()%>%as.Date("%d-%m-%y")
pathConfirmed<-paste(cwd,"/data/confirmedCases_",dateDownloaded,".csv",sep="")
pathDeath<-paste(cwd,"/data/deathsCases_",dateDownloaded,".csv",sep="")

if(.Platform$OS.type == "windows") {
  download.file(confirmedURL_JHU,destfile = pathConfirmed)
  download.file(deathURL_JHU,destfile = pathDeath)
  #download.file(gitGermanyURL,destfile = pathGithubGermany)
  } else { 
    download.file(confirmedURL_JHU,destfile = pathConfirmed, method = "curl")
    download.file(deathURL_JHU,destfile = pathDeath, method = "curl")
    #download.file(gitGermanyURL,destfile = pathGithubGermany, method = "curl")
    }


#download.file(confirmedURL_JHU,destfile = pathConfirmed, method = "curl")
#download.file(deathURL_JHU,destfile = pathDeath)
```

